# Cargo configuration
# Note: CXXFLAGS must be set as an environment variable
# This file documents the requirement but doesn't set it directly
# The C++ standard is set to C++17 via CXXFLAGS environment variable
# in watch.sh and other build scripts

